CapaPresentacionTienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CapaEntidad;
using CapaNegocio;
using System.IO;
using System.Web.Services.Description;
using System.Threading.Tasks;
using System.Data;
using System.Globalization;
using CapaPresentacionTienda.Filter;
using Stripe.Checkout;
using Stripe;



namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DetalleProducto(int idproducto = 0)
        {
            Producto oProducto = new Producto();
            bool conversion;

            oProducto = new CN_Producto().Listar().Where(p => p.idProducto == idproducto).FirstOrDefault();

            if(oProducto != null)
            {
                oProducto.Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.rutaImagen, oProducto.nombreImagen), out conversion);
                oProducto.Extension = Path.GetExtension(oProducto.nombreImagen);
            }
            return View(oProducto);
        }

        [HttpGet]
        public JsonResult ListaCategorias()
        {
            List<Categoria> lista = new List<Categoria>();
            lista = new CN_Categoria().Listar();
            return Json(new{ data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarMarcaporCategoria(int idcategoria)
        {
            List<Marca> lista = new List<Marca>();
            lista = new CN_Marca().ListarMarcaporCategoria(idcategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarProducto(int idcategoria, int idmarca)
        {
            List<Producto> lista = new List<Producto>();

            bool conversion;

            lista = new CN_Producto().Listar().Select(p => new Producto()
            {
                idProducto = p.idProducto,
                nombre = p.nombre,
                descripcion = p.descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                precio = p.precio,
                stock = p.stock,
                rutaImagen = p.rutaImagen,
                Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.rutaImagen, p.nombreImagen), out conversion),
                Extension = Path.GetExtension(p.nombreImagen),
                activo = p.activo
            }).Where(p =>
                p.oCategoria.idCategoria == (idcategoria == 0 ? p.oCategoria.idCategoria : idcategoria) && 
                p.oMarca.idMarca == (idmarca == 0 ? p.oMarca.idMarca : idmarca) &&
                p.stock > 0 && p.activo == true
            ).ToList();

            var jsonresult = Json(new {data = lista}, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int .MaxValue;

            return jsonresult;
        }

        [HttpPost]
        public JsonResult AgregarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).idCliente;

            bool existe = new CN_Carrito().ExisteCarrito(idcliente, idproducto);

            bool respuesta = false;
            string mensaje = string.Empty;

            if(existe)
            {
                mensaje = "El producto ya existe en el carrito";
            }
            else
            {
                respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);
            }
            return Json(new {respuesta = respuesta, mensaje = mensaje}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).idCliente;
            int cantidad = new CN_Carrito().CantidadEnCarrito(idcliente);

            return Json(new {cantidad = cantidad}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult LitarProductosCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).idCliente;

            List<Carrito> oLista = new List<Carrito>();

            bool conversion;

            oLista = new CN_Carrito().ListarProducto(idcliente).Select(oc => new Carrito()
            {
                oProducto = new Producto()
                {
                    idProducto = oc.oProducto.idProducto,
                    nombre = oc.oProducto.nombre,
                    oMarca = oc.oProducto.oMarca,
                    precio = oc.oProducto.precio,
                    rutaImagen = oc.oProducto.rutaImagen,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oProducto.rutaImagen, oc.oProducto.nombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.oProducto.nombreImagen)
                },
                cantidad = oc.cantidad
            }).ToList();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult OperacionCarrito(int idproducto, bool sumar)
        {
            int idcliente = ((Cliente)Session["Cliente"]).idCliente;

            bool respuesta = false;
            string mensaje = string.Empty;

            //respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);

            //respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true(sumar), out mensaje);
            //respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, sumar, out mensaje);
            respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, sumar, out mensaje);



            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).idCliente;

            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Carrito().EliminarCarrito(idcliente, idproducto);


            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerCiudad()
        {
            List<Ciudad> oLista = new List<Ciudad>();

            oLista = new CN_Ubicacion().ObtenerCiudad();
                              
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
          public JsonResult ObtenerSector()
          {

              List<Sector> oLista = new CN_Ubicacion().ObtenerSector();
              return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
          }


        [ValidarSession]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }

        [HttpPost]

      

         public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
         {
             decimal total = 0;

             DataTable detalle_venta = new DataTable();

             detalle_venta.Locale = new CultureInfo("es-RD");
             detalle_venta.Columns.Add("IdProducto", typeof(string));
             detalle_venta.Columns.Add("Cantidad", typeof(int));
             detalle_venta.Columns.Add("Total", typeof(decimal));

            // Esto es solo para las prubas INICIO

            List<Producto> oListaProducto = new List<Producto>();

           /* foreach (Carrito oCarrito in oListaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(oCarrito.cantidad.ToString()) * oCarrito.oProducto.precio;
                total += subtotal;


                Producto nuevoProducto = new Producto
                {
                    idProducto = oCarrito.oProducto.idProducto,
                    nombre = oCarrito.oProducto.nombre,
                    descripcion = oCarrito.oProducto.descripcion,
                    precio = oCarrito.oProducto.precio,
                   
                    
                };

                
                oListaProducto.Add(nuevoProducto);

                
                detalle_venta.Rows.Add(new object[]
                {
                    oCarrito.oProducto.idProducto,
                    oCarrito.cantidad,
                    subtotal
                });
            }

                   string return_url= "https://localhost:44394/"*/





            //FIN

              foreach (Carrito oCarrito in oListaCarrito)
              {
                  decimal subtotal = Convert.ToDecimal(oCarrito.cantidad.ToString()) * oCarrito.oProducto.precio;
                  total += subtotal;


                  detalle_venta.Rows.Add(new object[]
                  {
              oCarrito.oProducto.idProducto,
              oCarrito.cantidad,
              subtotal
                  });
              }


              oVenta.montoTotal = total;
              oVenta.idCliente = ((Cliente)Session["Cliente"]).idCliente;
              oVenta.TotalProducto = oListaCarrito.Count;

              TempData["Venta"] = oVenta;
              TempData["DetalleVenta"] = detalle_venta;



            return Json(new { Status = true, Link = "/Tienda/PagoEfectuado?idTransaccion=code0001&status=true" }, JsonRequestBehavior.AllowGet);


         }



        [ValidarSession]
        [Authorize]

        public async Task<ActionResult> PagoEfectuado()
        {
            string idtransaccion = Request.QueryString["idTransaccion"];
            bool status = Convert.ToBoolean(Request.QueryString["status"]);
           // string token = Request.QueryString["token"];

            /*CN_Paypal opaypal = new CN_Paypal();
            Response_Paypal<Response_Capture> response_Paypal = new Response_Paypal<Response_Capture>();

CapaPresentacionTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="d-flex flex-column min-vh-100">

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid px-4">
            <a class="navbar-brand" href="@Url.Action("Index","Tienda")">Mi tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Tienda")">Inicio</a></li>
                    @*<li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>*@
                </ul>
                <form class="d-flex">
                    @if (Session["Cliente"] == null)
                    {
                        <a class="btn btn-outline-dark" aria-current="page" href="@Url.Action("Index", "Acceso")"><i class="fa-fast-backward fa-sign-out-alt me-1"></i> Iniciar Sesión</a>
                    }
                    else
                    {

                        <a class="btn btn-outline-dark" href="@Url.Action("Carrito","Tienda")">
                            <i class="fas fa-shopping-cart me-1"></i>
                            Carrrito
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cantidadcarrito">0</span>
                        </a>

                        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("MisCompras","Tienda")">Mis compras</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion", "Acceso")">Cerrar sesión</a></li>

                                </ul>
                            </li>
                        </ul>
                    }

                </form>
            </div>
        </div>
    </nav>
    @RenderBody()
   

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

<script>

    $(document).ready(function () {
        MostrarCantidadCantidadCarrito();
        
    })


    // Todo esto está bien en caso de errores, solo verifica la pate de arriba del document
    function MostrarCantidadCantidadCarrito() {

        if ($("#cantidadcarrito").length > 0) {
                
        jQuery.ajax({
            url: '@Url.Action("CantidadEnCarrito","Tienda")',
            type: "GET",
            dataType: "json",
            conteType: "application/json; charset=utf-8",
            success: function (data) {
                $("#cantidadcarrito").text(data.cantidad)
            }
           
            
        });

            }
        }
    </script>
</body>
</html>